
sources:
  - name: s1
    database: db_sales
    schema: dev_schema
    tables:
      - name: employees
      - name: tbl_customer
      - name: customers
      - name: orders
      - name: payments
      - name: tbl_ticket_info